### PR TITLE
remove routing to fix nickname being lost on refresh

### LINKED ISSUE #20: Nickname of user is lost upon page refresh
When the user is in the game room, if the user refreshes the page, the user's nickname will be lost and will no longer be able to play, although the user will still remain in the game room.

### PR DESCRIPTION
**Pull request by kev-inc**
fix #20 
also fixed another bug where the player is added for a second into the room when the user is not allowed inside

### CODE REVIEW

**Comment by kev-inc** [comment]
fix #34

File: gibberish_client/src/components/Gameroom/GameroomPage.js [hunk 1]
```diff
@@ -1,21 +1,21 @@
...
 const ROUND_ENDED_TIME = 5
 
 class GameroomPage extends React.Component {
 
 	constructor(props) {
 		super(props)
 		this.state = {
-			roomId: props.match.params.id,
+			nickname: props.nickname,
+			roomId: props.roomId,
```
Comment (KerrynEer) [inline gibberish_client/src/components/Gameroom/GameroomPage.js:18]: I think it will be better if we don't set nickname and roomId as states as this creates a second source of truth. 
We can just access `nickname `and `roomId `from props directly instead when we need it :)
